"""add rate_counters cross-instance limiter

Revision ID: 993d75032689
Revises: c3f2a9b41d77
Create Date: 2026-06-30 09:19:12.625537
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993d75032689'
down_revision: Union[str, None] = 'c3f2a9b41d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('bucket', sa.String(length=64), nullable=False),
    sa.Column('window_key', sa.BigInteger(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject', 'bucket', 'window_key', name='uq_rate_counter_window')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_counters')
    # ### end Alembic commands ###
